[tox]
requires = tox-uv>=1
envlist = django{42,52},coverage,quality

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    django42: django42
    django52: test
commands =
    pytest

[testenv:coverage]
runner = uv-venv-lock-runner
dependency_groups = test
commands =
    coverage run -m pytest

[testenv:quality]
runner = uv-venv-lock-runner
dependency_groups = quality
commands =
    pycodestyle src/invideoquiz/
    pylint src/invideoquiz/
